FROM jetbrains/teamcity-minimal-agent

RUN apt-get update -y && apt-get install -y sudo git bzip2 software-properties-common build-essential
RUN curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
RUN apt-get update -y && apt-get install -y nodejs
RUN sudo npm install -g phantomjs-prebuilt@2.1.16 yarn@1.5.1 --ignore-scripts
RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
RUN sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
RUN sudo apt-get update
RUN sudo apt-cache policy docker-ce
RUN sudo apt-get install -y docker-ce